### ISSUE TITLE
Insignificant application.

### ISSUE THREAD

**Issue by win1010525** [laobamac/hackinstoshTool#1]
* 既然是镜像下载，为什么不内置下载引擎，反倒跳转下载？
* 镜像下载为什么不套用gibmacos，可以下一切版本，而软件内置版本不全
* 没有提供basesystem的dmg下载及其chunklist
* efi那里建议用cpu架构代号，只说代数没有意义，存在特别多特殊型号
* 驱动那里没有itlwm，而且为什么不标注驱动版本？或者commit版本也行
* 查看可装性列表可以优化一下
* 10系n卡 webdriver支持macOS12

## 总之有很大优化空间

**Comment by laobamac** [comment]
1.云服务器之用来储存地址，高带宽大硬盘的负担不起，一个免费软件哪来的钱。
2.镜像下载都是用的悦享，看你像恢复系统。
3.有itlwm，请你仔细看下。
4.那不是列表，打字太丑，所以做的下拉框。
5.看你像webdriver，强制干的叫驱动，不是支持。我说了可以上，好好看。还支持，移植web还能30系呢。

**Comment by win1010525** [comment]
1. gibmacOS使你不需要存储镜像
2. basesystem不是恢复系统
3. airportitlwm需要区分系统
4. 照样很丑，并且不合逻辑
5. web不能移植30系，建议你学学iokit

**Comment by laobamac** [comment]
> 2\. basesystem

basesystem是恢复系统，建议你自己去看。
好好看我的恢复，看完再说话。
没有做任何ui，也没有时间做UI。直接堆的按钮。
移植可视30系，只是你不会。

**Comment by win1010525** [comment]
> > 2. basesystem
> 
> basesystem是恢复系统，建议你自己去看。 好好看我的回复，看完再说话。 没有做任何ui，也没有时间做UI。直接堆的按钮。 移植可视30系，只是你不会。

30系可以的话，还是建议你自己写一个驱动给大家用
basesystem是独立于macOS自带的recoveryOS之外的，我这里不想计较概念
你的软件的确存在的问题你并没有考虑解决，你的第一反应是对线，既然如此，我也不会提供任何建议了

**Comment by win1010525** [comment]
> 1.云服务器之用来储存地址，高带宽大硬盘的负担不起，一个免费软件哪来的钱。
> 2.镜像下载都是用的悦享，看你像恢复系统。
> 3.有itlwm，请你仔细看下。
> 4.那不是列表，打字太丑，所以做的下拉框。
> 5.看你像webdriver，强制干的叫驱动，不是支持。我说了可以上，好好看。还支持，移植web还能30系呢。
> 6.没有使用任何第三方组件，因为我不能用。即便这样都还会招来你们这种人。用了会更多。这是第一个版本，会更新更多的内容。你见过微信1.0.吗？处理发消息什么都用不了。你见过qq1.0吗？处理发消息什么都干不了。你在这里看着第一个版本就说这样的话，素质可见一斑。

和是不是1.0没有关系，gibmacOS没有禁止任何人用吧，而且你加个basesystem下载器只需要保证源代码不做修改，没有人要求过你禁止使用

**Comment by laobamac** [comment]
> > > 2. basesystem
> > 
> > 
> > basesystem是恢复系统，建议你自己去看。 好好看我的回复，看完再说话。 没有做任何ui，也没有时间做UI。直接堆的按钮。 移植可视30系，只是你不会。
> 
> 30系可以的话，还是建议你自己写一个驱动给大家用 basesystem是独立于macOS自带的recoveryOS之外的，我这里不想计较概念 你的软件的确存在的问题你并没有考虑解决，你的第一反应是对线，既然如此，我也不会提供任何建议了

我也不想计较，Basesystem恢复系统，和recoveryOS完全不是一个东西，basesystem只要还能开机就能进。没禁止，我也想用，但是多数人的理解能力都跟你一样差劲。我很想收到你们的反馈，甚至我每天都起床第一一件事就是看私信。你看看我给你的恢复，我很期待是什么问题。但是你的态度实在是令我作呕。

**Comment by laobamac** [comment]
> > 1.云服务器之用来储存地址，高带宽大硬盘的负担不起，一个免费软件哪来的钱。
> > 2.镜像下载都是用的悦享，看你像恢复系统。
> > 3.有itlwm，请你仔细看下。
> > 4.那不是列表，打字太丑，所以做的下拉框。
> > 5.看你像webdriver，强制干的叫驱动，不是支持。我说了可以上，好好看。还支持，移植web还能30系呢。
> > 6.没有使用任何第三方组件，因为我不能用。即便这样都还会招来你们这种人。用了会更多。这是第一个版本，会更新更多的内容。你见过微信1.0.吗？处理发消息什么都用不了。你见过qq1.0吗？处理发消息什么都干不了。你在这里看着第一个版本就说这样的话，素质可见一斑。
> 
> 和是不是1.0没有关系，gibmacOS没有禁止任何人用吧，而且你加个basesystem下载器只需要保证源代码不做修改，没有人要求过你禁止使用 而且我小新air14iml的多basesystem镜像从第一版就能用，如果你认为1.0的release就可以摆烂的话还是请便吧

那你就不要提建议了，慢走不送。

**Comment by win1010525** [comment]
你应该仔细想想你这个软件目前有没有意义，是否有东西能取代它，总之重复造轮子的项目只能上b站上很多小白看到，其他人并不会对你的项目有所帮助的

**Comment by laobamac** [comment]
> 你应该仔细想想你这个软件目前有没有意义，是否有东西能取代它，总之重复造轮子的项目只能上b站上很多小白看到，其他人并不会对你的项目有所帮助的

只要存在当然是有意义的，只不过是时间问题。等着时间啦，会进步的
